# Generated by Django 3.2.5 on 2021-07-23 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driver', '0001_initial'),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeRequest', models.DateTimeField(null=True)),
                ('loadToDriver', models.BooleanField()),
                ('longitude', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('deadlineTime', models.DateTimeField()),
                ('arriveTime', models.DateTimeField()),
                ('driverId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.driver')),
                ('restaurantId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
