# Generated by Django 2.2.13 on 2021-08-15 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order',
        ),
    ]
